name: bachelor
channels:
  - conda-forge
  - pytorch
dependencies:
  - accelerate
  - black
  - flake8
  - flake8-bugbear
  - flake8-pie
  - flake8-simplify
  - ipdb
  - ipykernel
  - isort
  - lxml
  - matplotlib
  - mypy
  - nbconvert
  - neovim
  - nltk
  - notebook
  - numpy
  - pandas
  - pip
  - pip-tools
  - pyphen
  - python=3.12
  - pytorch
  - pytorch-cuda
  - pyupgrade
  - regex
  - scikit-learn
  - seaborn
  - tokenizers
  - pip:
    - evaluate
    - flake8-typing-imports
    - pandas-stubs
    - types-regex
